# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-22 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default='d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default='n', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='short_description',
            field=models.CharField(default='sd', max_length=255),
            preserve_default=False,
        ),
    ]
