# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-27 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20161127_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='assistent',
            new_name='assistant',
        ),
    ]
